package main

// wizTerm 条款字典的一行（一个 key 对应 10 种语言）。字段顺序固定：zh,en,ja,ko,fr,de,es,pt,ru,vi。
type wizTerm struct {
	code                                     string
	zh, en, ja, ko, fr, de, es, pt, ru, vi   string
}

// wizTermRows 条款数据，由 init 组装为 wizDictTerms 映射。
var wizTermRows = []wizTerm{
	{"term1", "一、服务说明", "1. About this service", "1. このサービスのご説明", "1. 서비스 소개", "1. Le service", "1. Über diesen Dienst", "1. Acerca del servicio", "1. Sobre este serviço", "1. О сервисе", "1. Về dịch vụ"},
	{"term1_body", "Tsumugi 是基于 Go 标准库实现的轻量级内存数据库，提供原生二进制协议与 MySQL 兼容协议。本软件按「现状」提供，不附带任何保证。", "Tsumugi is a lightweight in-memory database built with the Go standard library, offering a native binary protocol and MySQL compatibility. Provided \"as is\", without any warranty.", "Tsumugi（つむぎ）は Go 標準ライブラリ製の軽量インメモリデータベースで、バイナリと MySQL 互換プロトコルを提供します。本ソフトは無保証で提供されます。", "Tsumugi(つむぎ)는 Go 표준 라이브러리 기반 인메모리 데이터베이스입니다. 바이너리·MySQL 호환 프로토콜을 제공하며, 보증 없이 \"있는 그대로\" 제공됩니다.", "Tsumugi (つむぎ) est une base de données en mémoire légère en Go, avec protocole binaire natif et compatibilité MySQL. Fourni « en l'état », sans garantie.", "Tsumugi (つむぎ) ist eine leichte In-Memory-Datenbank in Go mit Binärprotokoll und MySQL-Kompatibilität. Bereitgestellt ohne jegliche Garantie.", "Tsumugi (つむぎ) es una base de datos ligera en memoria en Go, con protocolo binario y compatibilidad con MySQL. Se ofrece «tal cual», sin garantías.", "O Tsumugi (つむぎ) é uma base de dados leve em Go, com protocolo binário e compatibilidade MySQL. Fornecido \"como está\", sem garantias.", "Tsumugi — лёгкая in-memory СУБД на Go с нативным и MySQL-совместимым протоколами. Поставляется «как есть», без гарантий.", "Tsumugi là CSDL trong bộ nhớ viết bằng Go, hỗ trợ giao thức nhị phân và MySQL. Cung cấp \"nguyên trạng\", không bảo đảm."},
	{"term2", "二、开源协议", "2. Open-source license", "2. オープンソースライセンス", "2. 오픈소스 라이선스", "2. Licence open source", "2. Open-Source-Lizenz", "2. Licencia de código abierto", "2. Licença de código aberto", "2. Open-Source-лицензия", "2. Giấy phép mã nguồn mở"},
	{"term2_body", "本项目基于 MIT License 开源，可自由使用、修改、分发与商用。完整文本见根目录 LICENSE 文件。", "Released under the MIT License. Free to use, modify, distribute and use commercially. See LICENSE at the project root.", "MIT License で公開されています。利用・変更・配布・商用利用は自由です。全文は LICENSE ファイルをご覧ください。", "MIT License로 공개되어 자유롭게 사용·수정·배포·상업 이용할 수 있습니다. 전문은 LICENSE 파일을 참고하세요.", "Publié sous licence MIT. Libre d'utilisation, de modification, de distribution et d'exploitation commerciale. Voir LICENSE.", "Unter der MIT-Lizenz veröffentlicht. Frei nutzbar, änderbar, verteilbar und kommerziell einsetzbar. Siehe LICENSE.", "Publicado bajo MIT License. Libre de usar, modificar, distribuir y usar comercialmente. Ver LICENSE.", "Publicado sob MIT License. Livre para usar, modificar, distribuir e comercializar. Ver LICENSE.", "Распространяется по лицензии MIT. Свободное использование, изменение, распространение и коммерческое применение. См. LICENSE.", "Phát hành theo giấy phép MIT, tự do dùng, sửa, phân phối, thương mại. Xem LICENSE."},
	{"term3", "三、数据责任", "3. Data responsibility", "3. データの責任", "3. 데이터 책임", "3. Responsabilité des données", "3. Datenverantwortung", "3. Responsabilidad de los datos", "3. Responsabilidade dos dados", "3. Ответственность за данные", "3. Trách nhiệm dữ liệu"},
	{"term3_body", "用户应自行负责数据的备份与安全。Tsumugi 提供 WAL 持久化，但断电、硬件故障等极端场景下不保证数据完整，请定期备份。", "You are responsible for data backup and security. Tsumugi provides WAL persistence, but cannot guarantee integrity in extreme events such as power loss. Back up regularly.", "データのバックアップと安全は利用者の責任です。WAL 永続化を提供しますが、停電などの異常時は完全性を保証できません。定期バックアップしてください。", "데이터 백업과 보안은 사용자 책임입니다. WAL 영속화를 제공하지만 정전 같은 극단 상황에선 무결성을 보장하지 못합니다. 주기적으로 백업하세요.", "La sauvegarde des données est votre responsabilité. La persistance WAL est fournie, mais l'intégrité n'est pas garantie en cas d'incident. Sauvegardez régulièrement.", "Sie sind für die Datensicherung verantwortlich. WAL-Persistenz wird geboten, aber bei Stromausfall ist die Integrität nicht garantiert. Sichern Sie regelmäßig.", "Eres responsable de la copia y seguridad. Se ofrece persistencia WAL, sin garantía ante cortes. Haz copias con frecuencia.", "A segurança dos dados é sua responsabilidade. É fornecida persistência WAL, sem garantia em caso de falhas. Faça cópias com regularidade.", "За безопасность данных отвечаете вы. Обеспечивается WAL, но при сбоях целостность не гарантируется. Делайте резервные копии.", "Bạn chịu trách nhiệm sao lưu. Tsumugi có WAL nhưng không bảo đảm khi mất điện. Hãy sao lưu định kỳ."},
	{"term4", "四、安全与账户", "4. Security and accounts", "4. セキュリティとアカウント", "4. 보안 및 계정", "4. Sécurité et comptes", "4. Sicherheit und Konten", "4. Seguridad y cuentas", "4. Segurança e contas", "4. Безопасность и аккаунты", "4. Bảo mật và tài khoản"},
	{"term4_body", "请妥善保管账号密码，不要将管理权限授予未经授权的第三方。因密码泄露导致的问题，Tsumugi 不承担责任。", "Keep your credentials safe and do not grant management rights to unauthorized parties. Tsumugi is not liable for leaks.", "アカウント情報を大切に保管し、第三者に権限を渡さないでください。漏えいによる問題には責任を負いません。", "계정 정보를 안전히 보관하고 무단 제3자에게 권한을 주지 마세요. 유출로 인한 문제는 책임지지 않습니다.", "Gardez vos identifiants et ne cédez pas vos droits à des tiers. Tsumugi n'est pas responsable en cas de fuite.", "Bewahren Sie Zugangsdaten sicher auf und geben Sie keine Rechte weiter. Für Leaks haftet Tsumugi nicht.", "Guarda tus credenciales y no des permisos a terceros. Tsumugi no responde por filtraciones.", "Guarde as credenciais e não conceda direitos a terceiros. Tsumugi não se responsabiliza por fugas.", "Храните данные входа в безопасности, не передавайте права третьим лицам. За утечки Tsumugi не отвечает.", "Giữ kín thông tin đăng nhập, không trao quyền cho bên thứ ba. Lộ thông tin là bạn tự chịu."},
	{"term5", "五、合法使用", "5. Lawful use", "5. 法令の遵守", "5. 적법한 사용", "5. Usage légal", "5. Rechtmäßige Nutzung", "5. Uso legal", "5. Utilização legal", "5. Законность использования", "5. Sử dụng hợp pháp"},
	{"term5_body", "不得将 Tsumugi 用于违法行为，包括存储非法内容、发起攻击、未经授权访问他人系统或数据。", "Do not use Tsumugi for unlawful activities, including storing illegal content, launching attacks, or unauthorized access.", "違法行為には使用しないでください（違法コンテンツ保存、攻撃、無断アクセスなど）。", "불법 활동(불법 콘텐츠 저장, 공격, 무단 접근 등)에 사용하지 마세요.", "N'utilisez pas Tsumugi à des fins illégales : contenus illicites, attaques, accès non autorisé.", "Tsumugi nicht für illegale Zwecke nutzen (illegaler Inhalt, Angriffe, unbefugter Zugriff).", "No uses Tsumugi para fines ilegales: contenido ilícito, ataques o accesos no autorizados.", "Não use o Tsumugi para fins ilegais: conteúdo ilícito, ataques ou acesso não autorizado.", "Не используйте Tsumugi для противоправных действий: нелегальный контент, атаки, несанкционированный доступ.", "Không dùng Tsumugi cho hành vi bất hợp pháp: nội dung xấu, tấn công, truy cập trái phép."},
	{"term6", "六、资源与性能", "6. Resources and performance", "6. リソースと性能", "6. 리소스 및 성능", "6. Ressources et performance", "6. Ressourcen und Leistung", "6. Recursos y rendimiento", "6. Recursos e desempenho", "6. Ресурсы и производительность", "6. Tài nguyên và hiệu năng"},
	{"term6_body", "Tsumugi 是内存数据库，重启后由 WAL 恢复。请按硬件规划数据规模与写入频率；fsync 模式下性能取决于磁盘。", "Tsumugi is an in-memory database restored from WAL on restart. Plan your data size and write rate; in fsync mode, throughput depends on disk speed.", "インメモリデータベースで、再起動後は WAL から復元。ハードに合わせて設計してください。fsync モードではディスク性能に依存します。", "인메모리 DB로 재시작 시 WAL에서 복구됩니다. 하드웨어에 맞춰 설계하세요. fsync 모드는 디스크 성능에 영향받습니다.", "Base en mémoire restaurée depuis le WAL. Planifiez vos données; en mode fsync, les performances dépendent du disque.", "In-Memory-Datenbank, Wiederherstellung aus WAL. Planen Sie Datenvolumen; im fsync-Modus zählt die Disk-Leistung.", "Base en memoria restaurada desde el WAL. Planifica tus datos; en modo fsync importa el disco.", "BD em memória restaurada do WAL. Planeie os dados; em modo fsync o disco é determinante.", "СУБД в памяти, восстановление из WAL. Планируйте объём; в режиме fsync решает диск.", "CSDL trong bộ nhớ, khôi phục từ WAL. Hoạch dữ liệu theo phần cứng; fsync phụ thuộc đĩa."},
	{"term7", "七、隐私", "7. Privacy", "7. プライバシー", "7. 개인정보", "7. Confidentialité", "7. Datenschutz", "7. Privacidad", "7. Privacidade", "7. Конфиденциальность", "7. Quyền riêng tư"},
	{"term7_body", "Tsumugi 为开源软件，不收集用户数据。数据保存在用户自己的服务器上。", "Tsumugi is open source and does not collect user data. Your data stays on your own server.", "オープンソースであり、ユーザーデータは収集しません。データはご自身のサーバーに保存されます。", "오픈소스이며 사용자 데이터를 수집하지 않습니다. 데이터는 자신의 서버에 남아 있습니다.", "Logiciel open source sans collecte de données. Vos données restent sur votre serveur.", "Open Source, keine Datensammlung. Ihre Daten bleiben auf Ihrem Server.", "Código abierto sin recopilación de datos. Tus datos están en tu servidor.", "Código aberto, sem recolha de dados. Os dados ficam no seu servidor.", "Open Source, данные не собираются. Данные остаются на вашем сервере.", "Mã nguồn mở, không thu thập dữ liệu. Dữ liệu nằm trên máy chủ của bạn."},
	{"term8", "八、免责条款", "8. Disclaimer", "8. 免責事項", "8. 면책 조항", "8. Limitation de responsabilité", "8. Haftungsausschluss", "8. Exención de responsabilidad", "8. Exclusão de responsabilidade", "8. Отказ от ответственности", "8. Miễn trách nhiệm"},
	{"term8_body", "在法律允许的范围内，Tsumugi 开发者对使用或无法使用本软件造成的直接、间接或意外损失不承担责任。", "To the extent permitted by law, the developers are not liable for damages arising from the use or inability to use the software.", "法律の範囲内で、開発者は本ソフトの利用による直接的・間接的損害について責任を負いません。", "법이 허용하는 범위에서 개발자는 소프트웨어 사용으로 인한 직·간접 손해에 책임지지 않습니다.", "Dans les limites de la loi, les développeurs ne sont pas responsables des dommages liés à l'utilisation du logiciel.", "Soweit gesetzlich zulässig, haften die Entwickler nicht für Schäden aus der Nutzung der Software.", "Dentro de lo permitido, los desarrolladores no responden por daños derivados del uso del software.", "Nos limites da lei, os programadores não respondem por danos do uso do software.", "В пределах закона разработчики не несут ответственности за ущерб от использования ПО.", "Trong khuôn khổ pháp luật, nhà phát triển không chịu trách nhiệm về thiệt hại do dùng phần mềm."},
}